#!/usr/bin/env python3
"""update-settings.py - Merge generated model data into settings.json.

Reads data/models.json and data/verified.json, then MERGES into settings.json:
- "models" (keyed by provider slug) is regenerated - it is generated content.
  Expired providers are excluded.
- "api_keys" is merged, never reset: existing non-empty values are always
  kept, and missing/empty entries are filled from env vars. Your manually
  edited keys survive every run.
- Unknown top-level sections and the "settings" block are preserved verbatim;
  default_model is only set when currently empty.

Usage: python3 scripts/update-settings.py [--settings <path>]
Path precedence: --settings > FREELLM_SETTINGS env > <repo root>/settings.json
"""
import datetime
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.abspath(os.path.join(__file__, '..')))
MODELS_FILE = os.path.join(BASE, 'data', 'models.json')
VERIFIED_FILE = os.path.join(BASE, 'data', 'verified.json')

# settings api_keys slug -> env var that can fill it. Slugs match provider
# keys used in the models section; test-apis.py resolves either spelling.
ENV_KEYS = {
    'groq': 'GROQ_API_KEY',
    'google-gemini': 'GEMINI_API_KEY',
    'openrouter': 'OPENROUTER_API_KEY',
    'mistral-ai': 'MISTRAL_API_KEY',
    'cloudflare-workers-ai': 'CLOUDFLARE_API_KEY',
    'cerebras': 'CEREBRAS_API_KEY',
    'siliconflow': 'SILICONFLOW_API_KEY',
}


def _normk(s):
    return re.sub(r'[^a-z0-9]+', '', (s or '').lower()).removesuffix('apikey')


def defaults():
    return {
        "version": "2.0.0",
        "models": {},
        "api_keys": {},
        "settings": {
            "default_model": None,
            "rate_limits": {
                "requests_per_minute": 60,
                "requests_per_day": 10000
            },
            "cache": {
                "enabled": True,
                "ttl": 3600
            },
            "logging": {
                "level": "info",
                "save_responses": False
            }
        }
    }


def load_existing(settings_file):
    """Load the user's settings.json (or a template) WITHOUT discarding anything.

    A timestamped backup is taken first; the returned dict starts from the
    template and is overwritten by whatever the user already had.
    """
    settings = defaults()
    if not os.path.exists(settings_file):
        return settings
    backup = settings_file + '.backup.' + datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    os.rename(settings_file, backup)
    print(f'Backup: {backup}')
    try:
        existing = json.load(open(backup))
    except ValueError as e:
        print(f'warning: could not parse previous settings ({e}); starting from template')
        return settings
    if isinstance(existing, dict):
        for k, v in existing.items():
            if k == 'settings' and isinstance(v, dict):
                merged = dict(settings['settings'])
                merged.update(v)          # user's settings block wins
                settings['settings'] = merged
            else:
                settings[k] = v           # preserves models/api_keys/unknown keys
    return settings


def build_models(models_data, verified_data):
    """Build settings models section from generated data + verification info."""
    providers = {}

    # First, model records from data/models.json (generated by gather-x-apis.py)
    for m in models_data:
        provider_name = m.get('provider', '')
        status = m.get('status', 'unverified')

        # Skip expired providers
        if status == 'expired':
            print(f'  SKIP (expired): {provider_name}')
            continue

        model_entry = {
            "provider": provider_name,
            "base_url": m.get('base_url', ''),
            "base_url_source": m.get('base_url_source', 'unknown'),
            "auth": m.get('auth', 'api_key'),
            "verified_from_x": m.get('verified_from_x', False),
            "x_post_count": m.get('context_from_x', 0),
            "context_length": None,
            "rate_limits": m.get('rate_limits', {}),
            "claims_verdict": m.get('promo_warning'),
        }

        # Context/model-name only from entries that actually have a context
        # value; never invent a default (test-apis.py derives a real model id
        # from the provider's /models endpoint).
        for model in m.get('models', []):
            if model.get('context'):
                model_entry['context_length'] = model['context']
                model_entry['model_name'] = model.get('name', 'free')
                break

        providers[provider_name.lower().replace(' ', '-')] = {
            "display_name": provider_name,
            **model_entry
        }

    # Second, merge verification info from verified.json
    verified = verified_data.get('providers', {})
    for std_name, vdata in verified.items():
        key = std_name.lower().replace(' ', '-')
        vstatus = vdata.get('status', 'unverified')
        if key not in providers and vstatus == 'expired':
            # gather-x-apis already dropped it from models.json; don't resurrect it
            print(f'  SKIP (expired, from verified.json): {std_name}')
            continue
        if key in providers:
            providers[key]['verification'] = vdata.get('status', 'unverified')
            if vdata.get('api_base_url'):
                providers[key]['base_url'] = vdata['api_base_url']
                providers[key]['base_url_source'] = 'verified'
        elif std_name:
            entry = {
                "display_name": std_name,
                "provider": std_name,
                "base_url": vdata.get('api_base_url', ''),
                "base_url_source": 'verified' if vdata.get('api_base_url') else 'none',
                "auth": "api_key",
                "verified_from_x": False,
                "x_post_count": 0,
                "context_length": None,
                "rate_limits": {},
                "verification": vdata.get('status', 'unverified')
            }
            providers[key] = entry

    return providers


def merge_api_keys(existing_keys):
    """Fill missing/empty api_keys entries from env vars. Non-empty existing
    values (manual or previously stored) are never overwritten."""
    keys = dict(existing_keys) if isinstance(existing_keys, dict) else {}
    for slug, env_var in ENV_KEYS.items():
        val = os.environ.get(env_var, '')
        if not (val and len(val) > 3 and not val.startswith('YOUR_')):
            continue
        if 'placeholder' in val:
            continue
        match = next((k for k in keys if _normk(k) in (_normk(slug), _normk(env_var))), None)
        if match:
            if not keys[match]:
                keys[match] = val
                print(f'  api_keys.{match}: filled from {env_var}')
        else:
            keys[slug] = val
            print(f'  api_keys.{slug}: added from {env_var}')
    return keys


def main():
    settings_file = os.environ.get('FREELLM_SETTINGS') or os.path.join(BASE, 'settings.json')
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == '--settings' and i + 1 < len(args):
            settings_file = args[i + 1]
            i += 2
        elif args[i] == '--help':
            print(__doc__)
            sys.exit(0)
        else:
            print(f'Unknown arg: {args[i]}')
            sys.exit(1)
    if not os.path.isabs(settings_file):
        settings_file = os.path.abspath(settings_file)

    if not os.path.exists(MODELS_FILE):
        print(f'ERROR: {MODELS_FILE} not found. Run x-scan.sh and gather-x-apis.py first.')
        sys.exit(1)

    models_data = json.load(open(MODELS_FILE))
    verified_data = json.load(open(VERIFIED_FILE)) if os.path.exists(VERIFIED_FILE) else {'providers': {}}

    print(f'Loaded {len(models_data)} models from data/models.json')
    print(f'Loaded {len(verified_data.get("providers", {}))} verified records')

    # Merge into the user's existing settings (backup taken inside)
    settings = load_existing(settings_file)

    # Regenerate the models section (generated content)
    previous_keys = set(settings.get('models', {}) or {})
    providers = build_models(models_data, verified_data)
    settings['models'] = providers
    print(f'Models section: {len(providers)} providers '
          f'({len(previous_keys - set(providers))} dropped from previous file)')

    # Merge api_keys: existing values win; only empty entries are filled
    settings['api_keys'] = merge_api_keys(settings.get('api_keys'))

    # Set default only when the user has not chosen one
    if not settings['settings'].get('default_model'):
        for key, p in providers.items():
            if p.get('verification') in ('verified', 'active'):
                settings['settings']['default_model'] = key
                break

    with open(settings_file, 'w') as f:
        json.dump(settings, f, indent=2, ensure_ascii=False)
    print(f'Written: {settings_file}')

    # Summary
    verified = [p for p in providers.values() if p.get('verification') in ('verified', 'active')]
    unverified = [p for p in providers.values() if p.get('verification') not in ('verified', 'active')]
    print(f'\nSummary:')
    print(f'  Verified: {len(verified)} - {", ".join(p["display_name"] for p in verified)}')
    print(f'  Unverified: {len(unverified)}')
    print(f'\nNext steps:')
    print(f'  1. Set your API keys via env vars (export GROQ_API_KEY=...) or in {settings_file}')
    print(f'  2. Run: bash scripts/test-apis.sh')


main()
